[package]
name = "data_string"
version = "0.1.0"
authors = ["Robert Beard <robert.a.beard@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
